config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  resources :rooms
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  get 'pages/home'
  root 'rooms#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy, inverse_of: :room

end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
  belongs_to :user
  
  def as_json(options)
    super(options).merge(user_avatar_url: user.gravatar_url)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  def gravatar_url
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_messages

  def create
    @room_message = RoomMessage.create user: current_user, room: @room, message: params.dig(:room_message, :message)

    RoomChannel.broadcast_to @room, @room_message
  end

  protected

  def load_messages
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_rooms

  def index
    @rooms = Room.all   
  end

  def show
    @room_message = RoomMessage.new room: @room
    @room_messages = @room.room_messages.includes(:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_parameters)

    if @room.save
      flash[:success] = "Room #{@room.name} was created successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update_attributes(room_parameters)
      flash[:success] = "Room #{@room.name} was updated successfully"
      redirect_to rooms_path
    else
      render :new
    end
  end

  protected

  def load_rooms
    @rooms = Room.all
    @room = Room.find(params[:id]) if params[:id]
  end

  def room_parameters
    params.require(:room).permit(:name)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  # def gravatar_url(user)
  #   gravatar_id = Digest::MD5::hexdigest(user.email).downcase
  #   url = "https://gravatar.com/avatar/#{gravatar_id}.png"
  # end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.justify-content-between
  a.navbar-brand[href="#"]
    | The Chattarium
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  - if current_user
    .dropdown
      a#navbarDropdown.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
        |  <img class="avatar" src="
        = current_user.gravatar_url
        | "> 
        = current_user.username
      .dropdown-menu.dropdown-menu-right[aria-labelledby="navbarDropdown"]
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id="root" class="container">
      <%= yield %>
    </div
  </body>
</html>

app/views/pages/home.html.slim
h1 Pages#home
p Find me in app/views/pages/home

app/views/rooms/edit.html.slim
h1 
  | Editing Chat Room: 
  em #{@room.name}

= simple_form_for @room do |form|
  = form.input :name
  = form.submit "Save", class: 'btn btn-success'

app/views/rooms/index.html.slim
h1 hjello łurld

.row
  .col-12.col-md-3
    .mb-3
      = link_to new_room_path, class: "btn btn-primary" do
        |  Create a room 
    - if @rooms.present?
      nav.nav.flex-column
        - @rooms.each do |room|
          = link_to room.name, room_path(room), class: "nav-link room-nav-link"
    - else
      .text-muted
        |  The are no rooms 
  .col
    .alert.alert-primary
      h4.alert-heading
        |  Welcome to the RailsChat! 
      p
        |  Let's start!
      hr
      p
        |  You can create or join a room from the sidebar. 

app/views/rooms/new.html.slim
h1 Create a new Chat Room

= simple_form_for @room do |form|
  = form.input :name
  = form.submit "Save", class: 'btn btn-success'

app/views/rooms/show.html.slim
h1
  = @room.name
.row
  .col-12.col-md-3
    = link_to "All Rooms", :root
  .col
    .chat data-channel-subscribe="room" data-room-id= @room.id
      - @room_messages.each do |room_message|
        .chat-message-container
          .row.no-gutters
            .col-auto.text-center
              |  <img src="
              = room_message.user.gravatar_url
              | " class="avatar" alt=""> 
            .col
              .message-content
                p.mb-1
                  em= room_message.user.username + ": "
                  = room_message.message
                .text-right
                  small
                    = room_message.created_at

    = simple_form_for @room_message, remote: true do |form|
      .input-group.mb-3
        = form.input :message, as: :string, wrapper: false, label: false, input_html: { class: 'chat-input' }
        .input-group-append
          = form.submit "Send", class: 'btn btn-primary chat-input'
      = form.input :room_id, as: :hidden



.d-none[data-role="message-template"]
  .chat-message-container
    .row.no-gutters
      .col-auto.text-center
        img.avatar[src="" alt="" data-role="user-avatar"]
      .col
        .message-content
          p.mb-1[data-role="message-text"]
          .text-right
            small[data-role="message-date"]